services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: '1'
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app       # 挂载源代码
      - /app/node_modules     # 防止覆盖容器内的 node_modules
    networks:
      - app-network
    command: ["npm", "run", "dev", "--", "--host"]

networks:
  app-network:
    driver: bridge
